substitutions:
  _TAG_NAME: "${COMMIT_SHA}"
timeout: 1800s


steps:
# https://stackoverflow.com/questions/56469381/run-pytest-in-google-build-cloudbuild-yaml-to-determine-if-build-passes-or-not
- id: Run backend unit tests
  name: 'docker.io/library/python:3.9.7'
  entrypoint: /bin/sh
  args:
  - -c
  - |
    cd backend
    export PYTHONPATH=$(pwd)/src
    pip install -r requirements.txt
    pytest

- id: Run frontend unit tests
  name: 'gcr.io/cloud-builders/npm'
  entrypoint: /bin/sh
  args:
  - -c
  - |
    cd frontend
    npm install
    CI=1 npm test